Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [1]:
import numpy as np

def vander(vector, N, increasing):
    
    if not increasing:
        matrix= np.array([x**(N-1-i) for x in vector for i in range(N)]).reshape(vector.size,N)
    else:
        matrix= np.array([x**i for x in vector for i in range(N)]).reshape(vector.size,N)

    return matrix
        
print(vander(np.array([2,5,8,9]),3,increasing=False))
print(vander(np.array([2,5,8,9]),3,increasing=True))   


[[ 4  2  1]
 [25  5  1]
 [64  8  1]
 [81  9  1]]
[[ 1  2  4]
 [ 1  5 25]
 [ 1  8 64]
 [ 1  9 81]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
Note: Solution submitted via github must contain all the detailed steps.
3.Output

In [2]:
import numpy as np
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
#a=np.array([10,20,30,40,50,60,70,80,90,100])
k=3
N=len(a)
y=()
for i in range(0,(N-k+1)):
    x = []
    for j in range(i,k+i):
        x.append(a[j])
    y=sum(x)/k
    print(y)

5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
